name: Forum Sign-In

on:
  schedule:
    # 每天的 UTC 时间 6:00 运行（你可以根据需要调整时间）
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 使用最新的 3.x 版本的 Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run sign-in script
      env:
        USERNAME: ${{ secrets.FORUM_USERNAME }}
        PASSWORD: ${{ secrets.FORUM_PASSWORD }}
        BASE_URL: ${{ secrets.FORUM_BASE_URL }}
        QDXQ: ${{ secrets.FORUM_QDXQ }}
        TODAYSAY: ${{ secrets.FORUM_TODAYSAY }}
      run: |
        python sign_in.py
